openapi: 3.1.0
info:
  title: Lending
  description: |
    Lending makes the combination between members and books found in the catalog
  contact:
    email: annegret.junker@online-library.org
    name: Annegret Junker
    url: https://api.online-library.org
  version: 1.0.0
  x-api-id: c004ebd2-f9c6-4e21-aa41-826f8eaf4092
  x-audience: external-public
servers:
  - url: 'https://api.online-library.org/lending/'
security:
  - openIdConnect:
      - lending:read
      - lending:write
      - lending:admin
tags:
  - name: Lending
    description: All endpoints to add, update, delete lending entries
  - name: Reading list
    description: |
      All endpoints to manipulate reading lists. General reading lists are reading lists of members without tags
paths:
  /lending-entries:

    post:
      description: Creates a new lending entry
      operationId: createNewLendingEntry
      tags:
        - Lending
      security:
        - openIdConnect:
            - Lending:write
    get:
      description: |
        Searches for a lending entry by by book or member.
        Members can be given by their names or identifiers.
        A book can be given by authors, titles, or by its identifier.
      operationId: getLendingEntriesbyBookOrMember
  /lending-entries/{lendingEntryId}:
    get:
      description: Delivers back a single catalog entry based on its identifier
      operationId: getLendingEntryById
      tags:
        - Lending
      security:
        - openIdConnect:
            - Lending:read
    put:
      description: Changes a lending entry
      operationId: updateLendingEntryById
      tags:
        - Lending
      security:
        - openIdConnect:
            - lending:write
    delete:
      description: Marks a lending entry as returned - the entry itself remains
      operationId: deleteLendingEntryById
      tags:
        - Lending
      security:
        - openIdConnect:
            - lending:admin
  /lending-entries/{lendingEntryId}/review:
    put:
      description: Endpoint to add or update a review of a lending entry by the owner
      operationId: updateReviewLendingEntryById
    delete:
      description: Deletes a review of a lending entry by the member of the entry
      operationId: deleteReviewLendingEntryById
  /lending-entries/{lendingEntryId}/shares:
    post:
      description: |
        Add a new member to the shares of the lending entry.
        The share can only be added by the member of the entry.
        A member cannot add themselves to the sharing list.
      operationId: addShareToLendingEntryById
      security:
        - openIdConnect:
            - lending:write
    delete:
      description: |
        Cancels the invitation list to a lending entry
        The share can only be deleted by the member of the entry.
      operationId: deleteShareLendingEntryById
      security:
        - openIdConnect:
            - lending:write
  /reading-lists:
    get:
      description: |
        Delivers back the reading lists of a member or shared with them identified by their identifier.
        Only the member themselves has access to their reading list.
        The reading lists can be filtered by their tags.
        Attention, a tag can appear several times in a reading list-
      operationId: getReadingListsByMemberId
      tags:
        - Reading list
      security:
        - openIdConnect:
            - lending:read
    post:
      description: Creates a new reading list of a user
      operationId: createReadingListByMemberId
      tags:
        - Reading list
      security:
        - openIdConnect:
            - lending:write
  /reading-lists/{readingListId}:
    get:
      description: Delivers back the reading list of a member
      operationId: getReadingListByMemberAndReadingListId
      tags:
        - Reading list
      security:
        - openIdConnect:
            - lending:read
    put:
      description: Changes a reading list of a member
      operationId: updateReadingListByMemberAndReadingListId
      tags:
        - Reading list
      security:
        - openIdConnect:
            - lending:write
    delete:
      description: |
        A member can delete their reading list.
        The member needs to be the owner of the reading list.
        To so the reading list must not be shared with other members.
  /reading-lists/{readingListId}/tags:
    put:
      description: Endpoint to change a list of tags of a certain reading list, changes are only allowed by the owner
      operationId: updateTagsResultListById
      security:
        - openIdConnect:
            - lending:write
  /reading-lists/{readingListId}/shares:
    post:
      description: |
        Add a new member to the shares of the reading list.
        The share can only be added by the owner of the list.
        A member cannot add themselves to the sharing list.
      operationId: addShareToReadingListById
      security:
        - openIdConnect:
            - lending:write
    delete:
      description: |
        Cancels the invitation list to a reading list
        The reading list can only be deleted by the member of the entry.
      operationId:
        deleteShareOfReadingListById
      security:
        - openIdConnect:
            - lending:write
  /shares/{memberId}:
    get:
      description: Delivers back all shares of a member
      operationId: getSharesByMember
components:
  securitySchemes:
    openIdConnect:
      type: openIdConnect
      description: Security scheme for events
      openIdConnectUrl: "https://idp.codecentric.de/configuration"
