openapi: 3.1.0
info:
  title: Catalog Factory
  description: API to write new catalog entries or to change existing ones.
  contact:
    email: annegret.junker@codecentric.de
    name: Annegret Junker
  version: 1.0.0
  x-api-id: c004ebd2-f9c6-4e21-aa41-826f8eaf4092
  x-audience: external-public
servers:
  - url: 'https://api.mycompany.de/catalog-factory-service'
security:
  - openIdConnect:
      - resource:read
      - resource:write
      - resource:admin
tags:
  - name: Catalog entries
    description: All endpoints handling catalog entries.
paths:
  /resources:
    get:
      description: Description # describe your function
      # define a unique operationId
      operationId: getResourceByFilterCriteria
      tags:
        - Name Tag
      security:
        - openIdConnect:
            - resource:read
      parameters:
        - $ref: '#/components/parameters/SearchCriteriasParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '200':
          $ref: '#/components/responses/ResourceListResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

    post:
      description: Description # describe your function
      # define a unique operationId
      operationId: createNewRessource
      tags:
        - Name Tag
      security:
        - openIdConnect:
            - resource:write
      parameters:
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        # link to your resource to be created
        $ref: '#/components/requestBodies/ResourceToBeCreatedRequest'
      responses:
        '201':
          $ref: '#/components/responses/LinkToResourceResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

  /resources/{resourceId}:
    get:
      description: Description # describe your function
      # define a unique operationId
      operationId: getResourceById
      tags:
        - Name Tag
      security:
        - openIdConnect:
            - resource:read
      parameters:
        - $ref: '#/components/parameters/ResourceIdentifierParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '200':
          # Answer with your resource
          $ref: '#/components/responses/SingleResourceResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

    put:
      description: Description # describe your function
      # define a unique operationId
      operationId: updateResourceById
      tags:
        - Name Tag
      security:
        - openIdConnect:
            - resource:write
      parameters:
        - $ref: '#/components/parameters/ResourceIdentifierParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        # Link to your resource to be updated
        $ref: '#/components/requestBodies/ResourceToBeChangedRequest'
      responses:
        '200':
          $ref: '#/components/responses/LinkToResourceResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

    delete:
      description: Description # describe your function
      # define a unique operationId
      operationId: deleteResourceById
      tags:
        - Name Tag
      security:
        - openIdConnect:
            - resource:admin
      parameters:
        - $ref: '#/components/parameters/ResourceIdentifierParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulOperationResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'


components:
  parameters:
    ResourceIdentifierParameter:
      name: resourceId
      description: Resource identifier
      required: true
      in: path
      schema:
        type: string
        format: uuid
        examples:
          - 448b5bc-a9bc-4036-8899-c77f781a76d5

    SearchCriteriasParameter:
      name: searchCriterias
      description: A single search criteria
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          minLength: 2
          maxLength: 200
          examples:
            - bla bla

    VersionParameter:
      name: x-version
      description: Version of the API specification used delivered in header
      in: header
      required: true
      schema:
        type: string
        # Give here the versions of your specification supported by your implementation
        x-extensible-enum:
          - 1.0.0
        default: 1.0.0
        examples:
          - 1.0.0


  responses:
    BadRequestResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'


    ForbiddenResponse:
      description: Forbidden

    LinkToResourceResponse:
      description: Successful operation - Catalog entry created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Link"

    NotFoundResponse:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'


    # Needs to be substituted by the resource you want to expose
    ResourceListResponse:
      description: List of the resource you want to expose
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntries'

    # Needs to be substituted by the resource you want to expose
    SingleResourceResponse:
      description: Delivers back the resource to be exposed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntry'

    ServiceNotAvailableResponse:
      description: Service not available
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    DefaultResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    SuccessfulOperationResponse:
      description: Successful operation


  requestBodies:
    # needs to be substituted by the resource you want to expose
    ResourceToBeCreatedRequest:
      description: Creates a new resource
      content:
        # could be an array in case a bunch of the resource should be created
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntryToBeCreated'

    ResourceToBeChangedRequest:
      # needs to be updated by the resource you want to expose
      description: Updates the resource provided
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntry'

  schemas:
    Error:
      description: An error object used for error responses
      type: object
      required:
        - title
        - status
        - timestamp
      properties:
        title:
          description: A short description of the problem using kebab-cases
          type: string
          minLength: 2
          maxLength: 255
          examples:
            - out-of-stock
        detail:
          description: |
            A human-readable description of the problem which can be used by technicians to solve the problem.
          type: string
          examples:
            - The item is currently out of stock.
        timestamp:
          description: Point in time when the error occurred
          type: string
          format: date-time
          examples:
            - 2024-07-01T23:32:54T+01:00
        traceparent:
          description: Tracking ID of the API journey
          type: string
          pattern: ^[0-9]{2}-[0-9a-z]{16}-[0-9a-z]{8}-[0-9a-z]{1}[0-9a-z]{1}$
          examples:
            - 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
        severity:
          description: Severity of the according error
          type: string
          enum:
            - FATAL
            - ERROR
            - WARNING
            - INFO
          examples:
            - ERROR

    Link:
      description: Link to an entity
      type: object
      required:
        - type
        - link
      properties:
        type:
          description: Not fully qualified type name of the object
          type: string
          minLength: 2
          maxLength: 155
          # adapt the examples with your exposed resource
          examples:
            - Resource
        link:
          description: URL to the according entity
          type: string
          format: uri
          examples:
            - https://api.aok.de/resource-management/resources/74d870fa-9e93-4ffd-907e-038c85e8bc20

    CatalogEntries:
      # needs t obe substituted by the resource you want to expose
      # Resource array to be delivered as bulk
      type: array
      minItems: 0
      maxItems: 127
      items:
        $ref: '#/components/schemas/CatalogEntry'

    CatalogEntry:
      description: An entry in the catalog
      type: object
      # allows some kind of polymorphism
      allOf:
        - $ref: '#/components/schemas/CatalogEntryToBeCreated'
      properties:
        id:
          description: Identifier of catalog entry
          type: string
          format: uuid
          examples:
            - 859e5ab3-b42b-4998-ac14-c723c89b352f

    # needs to be substituted by the resource you want to expose
    # To be created - usually the resource without identifier
    CatalogEntryToBeCreated:
      description: Catalog entry of a new book
      type: object
      required:
        # put here the properties which are mandatory for your resource
        - title
      properties:
        title:
          description: A property of your resource
          type: title
          # try to define your properties as precise as possible
          # use formats and patterns to limit th value area
          minLength: 2
          maxLength: 255
          examples:
            - 'Domain-driven Design: Tackling Complexity in the World of Software'

  securitySchemes:
    openIdConnect:
      type: openIdConnect
      description: Security scheme for events
      openIdConnectUrl: "https://idp.library.de/configuration"