openapi: 3.1.0
info:
  title: Pure technical API
  description: API without any business meaning
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /customers/guids:
    get:
      description: Delivers the GUID of a customer by its tenant and business partner number
      operationId: getCustomerByPartnerNumberAndTenant
      parameters:
        - name: tenant
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 3
        - name: businessPartnerNumber
          in: query
          schema:
            type: string
            minLength: 10
            maxLength: 10
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
  
